// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"time"
)

type TGoRetirement struct {
	ent.Schema
}

func (TGoRetirement) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id").Comment("auto increment primary key"),
		field.String("creation_tx").Default("").Comment("creation hash of the certificate"),
		field.String("creator_address").Default("").Comment("creator of the certificate"),
		field.String("beneficiary_address").Default("").Comment("beneficiary of the certificate"),
		field.Float("amount").Default(0).Comment("amount of retirement"),
		field.String("token_address").Default("").Comment("token address"),
		field.String("token_name").Default("").Comment("token name"),
		field.String("token_type").Default("").Comment("type of token such as nct, bct..."),
		field.Time("retirement_time").Comment("time of retirement"),
		field.Time("mtime").Comment("modify time").Default(time.Now()).UpdateDefault(time.Now),
		field.Time("ctime").Comment("create time").Default(time.Now())}
}
func (TGoRetirement) Edges() []ent.Edge {
	return nil
}
func (TGoRetirement) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "t_go_retirements"},
	}
}
