// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"toucan-leaderboard/ent/predicate"
	"toucan-leaderboard/ent/tgonft"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TGoNFTQuery is the builder for querying TGoNFT entities.
type TGoNFTQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TGoNFT
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TGoNFTQuery builder.
func (tnq *TGoNFTQuery) Where(ps ...predicate.TGoNFT) *TGoNFTQuery {
	tnq.predicates = append(tnq.predicates, ps...)
	return tnq
}

// Limit adds a limit step to the query.
func (tnq *TGoNFTQuery) Limit(limit int) *TGoNFTQuery {
	tnq.limit = &limit
	return tnq
}

// Offset adds an offset step to the query.
func (tnq *TGoNFTQuery) Offset(offset int) *TGoNFTQuery {
	tnq.offset = &offset
	return tnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tnq *TGoNFTQuery) Unique(unique bool) *TGoNFTQuery {
	tnq.unique = &unique
	return tnq
}

// Order adds an order step to the query.
func (tnq *TGoNFTQuery) Order(o ...OrderFunc) *TGoNFTQuery {
	tnq.order = append(tnq.order, o...)
	return tnq
}

// First returns the first TGoNFT entity from the query.
// Returns a *NotFoundError when no TGoNFT was found.
func (tnq *TGoNFTQuery) First(ctx context.Context) (*TGoNFT, error) {
	nodes, err := tnq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tgonft.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tnq *TGoNFTQuery) FirstX(ctx context.Context) *TGoNFT {
	node, err := tnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TGoNFT ID from the query.
// Returns a *NotFoundError when no TGoNFT ID was found.
func (tnq *TGoNFTQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tnq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tgonft.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tnq *TGoNFTQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := tnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TGoNFT entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TGoNFT entity is found.
// Returns a *NotFoundError when no TGoNFT entities are found.
func (tnq *TGoNFTQuery) Only(ctx context.Context) (*TGoNFT, error) {
	nodes, err := tnq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tgonft.Label}
	default:
		return nil, &NotSingularError{tgonft.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tnq *TGoNFTQuery) OnlyX(ctx context.Context) *TGoNFT {
	node, err := tnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TGoNFT ID in the query.
// Returns a *NotSingularError when more than one TGoNFT ID is found.
// Returns a *NotFoundError when no entities are found.
func (tnq *TGoNFTQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tnq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tgonft.Label}
	default:
		err = &NotSingularError{tgonft.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tnq *TGoNFTQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := tnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TGoNFTs.
func (tnq *TGoNFTQuery) All(ctx context.Context) ([]*TGoNFT, error) {
	if err := tnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tnq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tnq *TGoNFTQuery) AllX(ctx context.Context) []*TGoNFT {
	nodes, err := tnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TGoNFT IDs.
func (tnq *TGoNFTQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := tnq.Select(tgonft.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tnq *TGoNFTQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := tnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tnq *TGoNFTQuery) Count(ctx context.Context) (int, error) {
	if err := tnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tnq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tnq *TGoNFTQuery) CountX(ctx context.Context) int {
	count, err := tnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tnq *TGoNFTQuery) Exist(ctx context.Context) (bool, error) {
	if err := tnq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tnq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tnq *TGoNFTQuery) ExistX(ctx context.Context) bool {
	exist, err := tnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TGoNFTQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tnq *TGoNFTQuery) Clone() *TGoNFTQuery {
	if tnq == nil {
		return nil
	}
	return &TGoNFTQuery{
		config:     tnq.config,
		limit:      tnq.limit,
		offset:     tnq.offset,
		order:      append([]OrderFunc{}, tnq.order...),
		predicates: append([]predicate.TGoNFT{}, tnq.predicates...),
		// clone intermediate query.
		sql:    tnq.sql.Clone(),
		path:   tnq.path,
		unique: tnq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WalletPub string `json:"wallet_pub,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TGoNFT.Query().
//		GroupBy(tgonft.FieldWalletPub).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tnq *TGoNFTQuery) GroupBy(field string, fields ...string) *TGoNFTGroupBy {
	grbuild := &TGoNFTGroupBy{config: tnq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tnq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tnq.sqlQuery(ctx), nil
	}
	grbuild.label = tgonft.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WalletPub string `json:"wallet_pub,omitempty"`
//	}
//
//	client.TGoNFT.Query().
//		Select(tgonft.FieldWalletPub).
//		Scan(ctx, &v)
//
func (tnq *TGoNFTQuery) Select(fields ...string) *TGoNFTSelect {
	tnq.fields = append(tnq.fields, fields...)
	selbuild := &TGoNFTSelect{TGoNFTQuery: tnq}
	selbuild.label = tgonft.Label
	selbuild.flds, selbuild.scan = &tnq.fields, selbuild.Scan
	return selbuild
}

func (tnq *TGoNFTQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tnq.fields {
		if !tgonft.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tnq.path != nil {
		prev, err := tnq.path(ctx)
		if err != nil {
			return err
		}
		tnq.sql = prev
	}
	return nil
}

func (tnq *TGoNFTQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TGoNFT, error) {
	var (
		nodes = []*TGoNFT{}
		_spec = tnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TGoNFT).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TGoNFT{config: tnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tnq *TGoNFTQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tnq.querySpec()
	_spec.Node.Columns = tnq.fields
	if len(tnq.fields) > 0 {
		_spec.Unique = tnq.unique != nil && *tnq.unique
	}
	return sqlgraph.CountNodes(ctx, tnq.driver, _spec)
}

func (tnq *TGoNFTQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tnq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tnq *TGoNFTQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tgonft.Table,
			Columns: tgonft.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: tgonft.FieldID,
			},
		},
		From:   tnq.sql,
		Unique: true,
	}
	if unique := tnq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tnq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tgonft.FieldID)
		for i := range fields {
			if fields[i] != tgonft.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tnq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tnq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tnq *TGoNFTQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tnq.driver.Dialect())
	t1 := builder.Table(tgonft.Table)
	columns := tnq.fields
	if len(columns) == 0 {
		columns = tgonft.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tnq.sql != nil {
		selector = tnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tnq.unique != nil && *tnq.unique {
		selector.Distinct()
	}
	for _, p := range tnq.predicates {
		p(selector)
	}
	for _, p := range tnq.order {
		p(selector)
	}
	if offset := tnq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tnq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TGoNFTGroupBy is the group-by builder for TGoNFT entities.
type TGoNFTGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tngb *TGoNFTGroupBy) Aggregate(fns ...AggregateFunc) *TGoNFTGroupBy {
	tngb.fns = append(tngb.fns, fns...)
	return tngb
}

// Scan applies the group-by query and scans the result into the given value.
func (tngb *TGoNFTGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tngb.path(ctx)
	if err != nil {
		return err
	}
	tngb.sql = query
	return tngb.sqlScan(ctx, v)
}

func (tngb *TGoNFTGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tngb.fields {
		if !tgonft.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tngb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tngb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tngb *TGoNFTGroupBy) sqlQuery() *sql.Selector {
	selector := tngb.sql.Select()
	aggregation := make([]string, 0, len(tngb.fns))
	for _, fn := range tngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tngb.fields)+len(tngb.fns))
		for _, f := range tngb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tngb.fields...)...)
}

// TGoNFTSelect is the builder for selecting fields of TGoNFT entities.
type TGoNFTSelect struct {
	*TGoNFTQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tns *TGoNFTSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tns.prepareQuery(ctx); err != nil {
		return err
	}
	tns.sql = tns.TGoNFTQuery.sqlQuery(ctx)
	return tns.sqlScan(ctx, v)
}

func (tns *TGoNFTSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tns.sql.Query()
	if err := tns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
