// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"toucan-leaderboard/ent/predicate"
	"toucan-leaderboard/ent/tgoretirement"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TGoRetirementQuery is the builder for querying TGoRetirement entities.
type TGoRetirementQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TGoRetirement
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TGoRetirementQuery builder.
func (trq *TGoRetirementQuery) Where(ps ...predicate.TGoRetirement) *TGoRetirementQuery {
	trq.predicates = append(trq.predicates, ps...)
	return trq
}

// Limit adds a limit step to the query.
func (trq *TGoRetirementQuery) Limit(limit int) *TGoRetirementQuery {
	trq.limit = &limit
	return trq
}

// Offset adds an offset step to the query.
func (trq *TGoRetirementQuery) Offset(offset int) *TGoRetirementQuery {
	trq.offset = &offset
	return trq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (trq *TGoRetirementQuery) Unique(unique bool) *TGoRetirementQuery {
	trq.unique = &unique
	return trq
}

// Order adds an order step to the query.
func (trq *TGoRetirementQuery) Order(o ...OrderFunc) *TGoRetirementQuery {
	trq.order = append(trq.order, o...)
	return trq
}

// First returns the first TGoRetirement entity from the query.
// Returns a *NotFoundError when no TGoRetirement was found.
func (trq *TGoRetirementQuery) First(ctx context.Context) (*TGoRetirement, error) {
	nodes, err := trq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tgoretirement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (trq *TGoRetirementQuery) FirstX(ctx context.Context) *TGoRetirement {
	node, err := trq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TGoRetirement ID from the query.
// Returns a *NotFoundError when no TGoRetirement ID was found.
func (trq *TGoRetirementQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = trq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tgoretirement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (trq *TGoRetirementQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := trq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TGoRetirement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TGoRetirement entity is found.
// Returns a *NotFoundError when no TGoRetirement entities are found.
func (trq *TGoRetirementQuery) Only(ctx context.Context) (*TGoRetirement, error) {
	nodes, err := trq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tgoretirement.Label}
	default:
		return nil, &NotSingularError{tgoretirement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (trq *TGoRetirementQuery) OnlyX(ctx context.Context) *TGoRetirement {
	node, err := trq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TGoRetirement ID in the query.
// Returns a *NotSingularError when more than one TGoRetirement ID is found.
// Returns a *NotFoundError when no entities are found.
func (trq *TGoRetirementQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = trq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tgoretirement.Label}
	default:
		err = &NotSingularError{tgoretirement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (trq *TGoRetirementQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := trq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TGoRetirements.
func (trq *TGoRetirementQuery) All(ctx context.Context) ([]*TGoRetirement, error) {
	if err := trq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return trq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (trq *TGoRetirementQuery) AllX(ctx context.Context) []*TGoRetirement {
	nodes, err := trq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TGoRetirement IDs.
func (trq *TGoRetirementQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := trq.Select(tgoretirement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (trq *TGoRetirementQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := trq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (trq *TGoRetirementQuery) Count(ctx context.Context) (int, error) {
	if err := trq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return trq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (trq *TGoRetirementQuery) CountX(ctx context.Context) int {
	count, err := trq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (trq *TGoRetirementQuery) Exist(ctx context.Context) (bool, error) {
	if err := trq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return trq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (trq *TGoRetirementQuery) ExistX(ctx context.Context) bool {
	exist, err := trq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TGoRetirementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (trq *TGoRetirementQuery) Clone() *TGoRetirementQuery {
	if trq == nil {
		return nil
	}
	return &TGoRetirementQuery{
		config:     trq.config,
		limit:      trq.limit,
		offset:     trq.offset,
		order:      append([]OrderFunc{}, trq.order...),
		predicates: append([]predicate.TGoRetirement{}, trq.predicates...),
		// clone intermediate query.
		sql:    trq.sql.Clone(),
		path:   trq.path,
		unique: trq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreationTx string `json:"creation_tx,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TGoRetirement.Query().
//		GroupBy(tgoretirement.FieldCreationTx).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (trq *TGoRetirementQuery) GroupBy(field string, fields ...string) *TGoRetirementGroupBy {
	grbuild := &TGoRetirementGroupBy{config: trq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return trq.sqlQuery(ctx), nil
	}
	grbuild.label = tgoretirement.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreationTx string `json:"creation_tx,omitempty"`
//	}
//
//	client.TGoRetirement.Query().
//		Select(tgoretirement.FieldCreationTx).
//		Scan(ctx, &v)
//
func (trq *TGoRetirementQuery) Select(fields ...string) *TGoRetirementSelect {
	trq.fields = append(trq.fields, fields...)
	selbuild := &TGoRetirementSelect{TGoRetirementQuery: trq}
	selbuild.label = tgoretirement.Label
	selbuild.flds, selbuild.scan = &trq.fields, selbuild.Scan
	return selbuild
}

func (trq *TGoRetirementQuery) prepareQuery(ctx context.Context) error {
	for _, f := range trq.fields {
		if !tgoretirement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if trq.path != nil {
		prev, err := trq.path(ctx)
		if err != nil {
			return err
		}
		trq.sql = prev
	}
	return nil
}

func (trq *TGoRetirementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TGoRetirement, error) {
	var (
		nodes = []*TGoRetirement{}
		_spec = trq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TGoRetirement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TGoRetirement{config: trq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, trq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (trq *TGoRetirementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := trq.querySpec()
	_spec.Node.Columns = trq.fields
	if len(trq.fields) > 0 {
		_spec.Unique = trq.unique != nil && *trq.unique
	}
	return sqlgraph.CountNodes(ctx, trq.driver, _spec)
}

func (trq *TGoRetirementQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := trq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (trq *TGoRetirementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tgoretirement.Table,
			Columns: tgoretirement.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: tgoretirement.FieldID,
			},
		},
		From:   trq.sql,
		Unique: true,
	}
	if unique := trq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := trq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tgoretirement.FieldID)
		for i := range fields {
			if fields[i] != tgoretirement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := trq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := trq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := trq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := trq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (trq *TGoRetirementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(trq.driver.Dialect())
	t1 := builder.Table(tgoretirement.Table)
	columns := trq.fields
	if len(columns) == 0 {
		columns = tgoretirement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if trq.sql != nil {
		selector = trq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if trq.unique != nil && *trq.unique {
		selector.Distinct()
	}
	for _, p := range trq.predicates {
		p(selector)
	}
	for _, p := range trq.order {
		p(selector)
	}
	if offset := trq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := trq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TGoRetirementGroupBy is the group-by builder for TGoRetirement entities.
type TGoRetirementGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (trgb *TGoRetirementGroupBy) Aggregate(fns ...AggregateFunc) *TGoRetirementGroupBy {
	trgb.fns = append(trgb.fns, fns...)
	return trgb
}

// Scan applies the group-by query and scans the result into the given value.
func (trgb *TGoRetirementGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := trgb.path(ctx)
	if err != nil {
		return err
	}
	trgb.sql = query
	return trgb.sqlScan(ctx, v)
}

func (trgb *TGoRetirementGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range trgb.fields {
		if !tgoretirement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := trgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (trgb *TGoRetirementGroupBy) sqlQuery() *sql.Selector {
	selector := trgb.sql.Select()
	aggregation := make([]string, 0, len(trgb.fns))
	for _, fn := range trgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(trgb.fields)+len(trgb.fns))
		for _, f := range trgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(trgb.fields...)...)
}

// TGoRetirementSelect is the builder for selecting fields of TGoRetirement entities.
type TGoRetirementSelect struct {
	*TGoRetirementQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (trs *TGoRetirementSelect) Scan(ctx context.Context, v interface{}) error {
	if err := trs.prepareQuery(ctx); err != nil {
		return err
	}
	trs.sql = trs.TGoRetirementQuery.sqlQuery(ctx)
	return trs.sqlScan(ctx, v)
}

func (trs *TGoRetirementSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := trs.sql.Query()
	if err := trs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
