// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"toucan-leaderboard/ent/predicate"
	"toucan-leaderboard/ent/tuser"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TUserUpdate is the builder for updating TUser entities.
type TUserUpdate struct {
	config
	hooks    []Hook
	mutation *TUserMutation
}

// Where appends a list predicates to the TUserUpdate builder.
func (tu *TUserUpdate) Where(ps ...predicate.TUser) *TUserUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetWalletPub sets the "wallet_pub" field.
func (tu *TUserUpdate) SetWalletPub(s string) *TUserUpdate {
	tu.mutation.SetWalletPub(s)
	return tu
}

// SetWalletType sets the "wallet_type" field.
func (tu *TUserUpdate) SetWalletType(s string) *TUserUpdate {
	tu.mutation.SetWalletType(s)
	return tu
}

// SetUname sets the "uname" field.
func (tu *TUserUpdate) SetUname(s string) *TUserUpdate {
	tu.mutation.SetUname(s)
	return tu
}

// SetFace sets the "face" field.
func (tu *TUserUpdate) SetFace(s string) *TUserUpdate {
	tu.mutation.SetFace(s)
	return tu
}

// SetGender sets the "gender" field.
func (tu *TUserUpdate) SetGender(b bool) *TUserUpdate {
	tu.mutation.SetGender(b)
	return tu
}

// SetTwitter sets the "twitter" field.
func (tu *TUserUpdate) SetTwitter(s string) *TUserUpdate {
	tu.mutation.SetTwitter(s)
	return tu
}

// SetEmail sets the "email" field.
func (tu *TUserUpdate) SetEmail(s string) *TUserUpdate {
	tu.mutation.SetEmail(s)
	return tu
}

// SetAbout sets the "about" field.
func (tu *TUserUpdate) SetAbout(s string) *TUserUpdate {
	tu.mutation.SetAbout(s)
	return tu
}

// SetLastLoginTime sets the "last_login_time" field.
func (tu *TUserUpdate) SetLastLoginTime(t time.Time) *TUserUpdate {
	tu.mutation.SetLastLoginTime(t)
	return tu
}

// SetMtime sets the "mtime" field.
func (tu *TUserUpdate) SetMtime(t time.Time) *TUserUpdate {
	tu.mutation.SetMtime(t)
	return tu
}

// SetCtime sets the "ctime" field.
func (tu *TUserUpdate) SetCtime(t time.Time) *TUserUpdate {
	tu.mutation.SetCtime(t)
	return tu
}

// SetNillableCtime sets the "ctime" field if the given value is not nil.
func (tu *TUserUpdate) SetNillableCtime(t *time.Time) *TUserUpdate {
	if t != nil {
		tu.SetCtime(*t)
	}
	return tu
}

// Mutation returns the TUserMutation object of the builder.
func (tu *TUserUpdate) Mutation() *TUserMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TUserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	tu.defaults()
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TUserUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TUserUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TUserUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TUserUpdate) defaults() {
	if _, ok := tu.mutation.LastLoginTime(); !ok {
		v := tuser.UpdateDefaultLastLoginTime()
		tu.mutation.SetLastLoginTime(v)
	}
	if _, ok := tu.mutation.Mtime(); !ok {
		v := tuser.UpdateDefaultMtime()
		tu.mutation.SetMtime(v)
	}
}

func (tu *TUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tuser.Table,
			Columns: tuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: tuser.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.WalletPub(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldWalletPub,
		})
	}
	if value, ok := tu.mutation.WalletType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldWalletType,
		})
	}
	if value, ok := tu.mutation.Uname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldUname,
		})
	}
	if value, ok := tu.mutation.Face(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldFace,
		})
	}
	if value, ok := tu.mutation.Gender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: tuser.FieldGender,
		})
	}
	if value, ok := tu.mutation.Twitter(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldTwitter,
		})
	}
	if value, ok := tu.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldEmail,
		})
	}
	if value, ok := tu.mutation.About(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldAbout,
		})
	}
	if value, ok := tu.mutation.LastLoginTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuser.FieldLastLoginTime,
		})
	}
	if value, ok := tu.mutation.Mtime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuser.FieldMtime,
		})
	}
	if value, ok := tu.mutation.Ctime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuser.FieldCtime,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// TUserUpdateOne is the builder for updating a single TUser entity.
type TUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TUserMutation
}

// SetWalletPub sets the "wallet_pub" field.
func (tuo *TUserUpdateOne) SetWalletPub(s string) *TUserUpdateOne {
	tuo.mutation.SetWalletPub(s)
	return tuo
}

// SetWalletType sets the "wallet_type" field.
func (tuo *TUserUpdateOne) SetWalletType(s string) *TUserUpdateOne {
	tuo.mutation.SetWalletType(s)
	return tuo
}

// SetUname sets the "uname" field.
func (tuo *TUserUpdateOne) SetUname(s string) *TUserUpdateOne {
	tuo.mutation.SetUname(s)
	return tuo
}

// SetFace sets the "face" field.
func (tuo *TUserUpdateOne) SetFace(s string) *TUserUpdateOne {
	tuo.mutation.SetFace(s)
	return tuo
}

// SetGender sets the "gender" field.
func (tuo *TUserUpdateOne) SetGender(b bool) *TUserUpdateOne {
	tuo.mutation.SetGender(b)
	return tuo
}

// SetTwitter sets the "twitter" field.
func (tuo *TUserUpdateOne) SetTwitter(s string) *TUserUpdateOne {
	tuo.mutation.SetTwitter(s)
	return tuo
}

// SetEmail sets the "email" field.
func (tuo *TUserUpdateOne) SetEmail(s string) *TUserUpdateOne {
	tuo.mutation.SetEmail(s)
	return tuo
}

// SetAbout sets the "about" field.
func (tuo *TUserUpdateOne) SetAbout(s string) *TUserUpdateOne {
	tuo.mutation.SetAbout(s)
	return tuo
}

// SetLastLoginTime sets the "last_login_time" field.
func (tuo *TUserUpdateOne) SetLastLoginTime(t time.Time) *TUserUpdateOne {
	tuo.mutation.SetLastLoginTime(t)
	return tuo
}

// SetMtime sets the "mtime" field.
func (tuo *TUserUpdateOne) SetMtime(t time.Time) *TUserUpdateOne {
	tuo.mutation.SetMtime(t)
	return tuo
}

// SetCtime sets the "ctime" field.
func (tuo *TUserUpdateOne) SetCtime(t time.Time) *TUserUpdateOne {
	tuo.mutation.SetCtime(t)
	return tuo
}

// SetNillableCtime sets the "ctime" field if the given value is not nil.
func (tuo *TUserUpdateOne) SetNillableCtime(t *time.Time) *TUserUpdateOne {
	if t != nil {
		tuo.SetCtime(*t)
	}
	return tuo
}

// Mutation returns the TUserMutation object of the builder.
func (tuo *TUserUpdateOne) Mutation() *TUserMutation {
	return tuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TUserUpdateOne) Select(field string, fields ...string) *TUserUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated TUser entity.
func (tuo *TUserUpdateOne) Save(ctx context.Context) (*TUser, error) {
	var (
		err  error
		node *TUser
	)
	tuo.defaults()
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*TUser)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TUserMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TUserUpdateOne) SaveX(ctx context.Context) *TUser {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TUserUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TUserUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TUserUpdateOne) defaults() {
	if _, ok := tuo.mutation.LastLoginTime(); !ok {
		v := tuser.UpdateDefaultLastLoginTime()
		tuo.mutation.SetLastLoginTime(v)
	}
	if _, ok := tuo.mutation.Mtime(); !ok {
		v := tuser.UpdateDefaultMtime()
		tuo.mutation.SetMtime(v)
	}
}

func (tuo *TUserUpdateOne) sqlSave(ctx context.Context) (_node *TUser, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tuser.Table,
			Columns: tuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: tuser.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tuser.FieldID)
		for _, f := range fields {
			if !tuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.WalletPub(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldWalletPub,
		})
	}
	if value, ok := tuo.mutation.WalletType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldWalletType,
		})
	}
	if value, ok := tuo.mutation.Uname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldUname,
		})
	}
	if value, ok := tuo.mutation.Face(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldFace,
		})
	}
	if value, ok := tuo.mutation.Gender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: tuser.FieldGender,
		})
	}
	if value, ok := tuo.mutation.Twitter(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldTwitter,
		})
	}
	if value, ok := tuo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldEmail,
		})
	}
	if value, ok := tuo.mutation.About(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tuser.FieldAbout,
		})
	}
	if value, ok := tuo.mutation.LastLoginTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuser.FieldLastLoginTime,
		})
	}
	if value, ok := tuo.mutation.Mtime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuser.FieldMtime,
		})
	}
	if value, ok := tuo.mutation.Ctime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuser.FieldCtime,
		})
	}
	_node = &TUser{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
