// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TGoCache is the predicate function for tgocache builders.
type TGoCache func(*sql.Selector)

// TGoEns is the predicate function for tgoens builders.
type TGoEns func(*sql.Selector)

// TGoRetirement is the predicate function for tgoretirement builders.
type TGoRetirement func(*sql.Selector)

// TUser is the predicate function for tuser builders.
type TUser func(*sql.Selector)
